ARG ALPINE_VERSION=latest
FROM alpine:${ALPINE_VERSION}

# RUN apk update && \
#     apk upgrade -a

RUN addgroup -g 1000 appgroup && \
    adduser -D -G appgroup -u 1000 appuser

WORKDIR /app

RUN chown -R appuser:appgroup /app

USER appuser

CMD ["/bin/sh"]
